# Generated by Django 5.2 on 2025-04-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('tracks', models.TextField(blank=True, null=True)),
                ('lineup', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='img/covers/')),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_band', to='albums.band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_genre', to='albums.genre')),
            ],
        ),
    ]
